services:
  backend:
    build: ./Backend
    image: nailfighter/traverse:backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    environment:
      SUPABASE_URL: "https://traverse.shreyansh-dev.app/supabase"

  frontend:
    build: ./Frontend
    image: nailfighter/traverse:frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    environment:
      VITE_BACKEND_URL: "http://localhost:3000"
      VITE_SUPABASE_URL: "https://traverse.shreyansh-dev.app/supabase"
