services:
  backend:
    build: ./Backend
    image: nailfighter/traverse:backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    environment:
      SUPABASE_URL: "http://host.docker.internal:54321"

  frontend:
    build: ./Frontend
    image: nailfighter/traverse:frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    environment:
      VITE_BACKEND_URL: "http://host.docker.internal:3000"
      VITE_SUPABASE_URL: "http://host.docker.internal:54321"
