version: "3.8"

services:
  backend:
    build: ./Server
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    environment:
      SUPABASE_URL: "http://host.docker.internal:54321"

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    environment:
      VITE_BACKEND_URL: "http://host.docker.internal:3000"
      VITE_SUPABASE_URL: "http://host.docker.internal:54321"
